CREATE DATABASE practice1;
\c practice1
CREATE TABLE public.students (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_name character varying NOT NULL,
  first_name character varying NOT NULL,
  group_number character varying,
  age integer
);
INSERT INTO students (last_name, first_name, group_number, age) VALUES
 ('Иванов','Иван','ИВ-101',19),('Петрова','Мария','ИВ-101',20),('Сидоров','Алексей','ИВ-102',21);
SELECT * FROM students ORDER BY id;
UPDATE students SET age = 22 WHERE last_name = 'Иванов';
SELECT * FROM students ORDER BY id;
DELETE FROM students WHERE last_name = 'Сидоров';
SELECT * FROM students ORDER BY id;
CREATE TABLE public.teachers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_name character varying NOT NULL,
  first_name character varying NOT NULL,
  subject character varying,
  age integer
);
INSERT INTO teachers (last_name, first_name, subject, age) VALUES
 ('Смирнова','Елена','Базы данных',41),('Кузнецов','Андрей','Математика',37);
SELECT * FROM teachers ORDER BY id;
